- name : install and run nginx
  host : web
  become : yes # like -b sudo access adhoc command
  tasks :
    - name : install nginx server
      ansible.builtin.dnf:
        name : nginx
        state : latest
    - name : start nginx server
      ansible.builtin.service:
        name : nginx
        state : started
        enabled : yes    

        
  
